[package]
name = "frog-problem"
version = "0.1.0"
authors = ["ncoif <github@ncoif.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
